'use client';
import { useEffect, useRef, useState } from 'react';
import { io } from 'socket.io-client';
import { ArrowRight, ArrowUpRight, Check, Copy, Crown, Eraser, Globe2, Heart, HelpCircle, LogOut, MessageCircle, Pencil, Plus, Send, Settings2, Shuffle, Sparkles, Timer, Trash2, Trophy, Users, X, Zap } from 'lucide-react';
const avatars=['🐸','🐱','🐻','🐰','🦊','🐼'];
const colors=['#333333','#ef6251','#f6bd45','#79a86a','#679aca','#9870b6','#e79fba','#ffffff'];
function Doodle({type,className=''}) {return <svg className={className} viewBox="0 0 180 160" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{type==='flower'?<><path d="M91 105q-5 26 0 49m0-19q-37 0-35-25 28-1 35 25m2 6q32 0 36-25-29-1-36 25"/><path fill="#f2b657" d="M75 63C41 37 75 6 91 41c14-39 47-19 27 11 40-5 42 32 8 34 26 26-6 49-25 20-7 36-43 23-29-8-36 13-49-23-17-32Z"/><circle cx="94" cy="76" r="20" fill="#faf6ec"/><path d="M87 72v3m14-3v3m-14 8q7 7 14 0"/></>:type==='pencil'?<><path fill="#f0b94e" d="m44 112 69-87 27 22-69 87-35 13Z"/><path fill="#f0a39d" d="m113 25 12-14q6-7 13-1l15 12q7 6 1 13l-14 12Z"/><path fill="#f8edce" d="m44 112 27 22-35 13Z"/><path d="m53 119 69-86M36 147l6-18"/></>:type==='planet'?<><circle cx="91" cy="80" r="44" fill="#aaa0cd"/><path d="M46 73C-6 93 20 119 91 99S178 48 133 52M51 64C19 66-3 94 44 101m91-11c41-11 38-34 3-35"/><path d="m79 51 9-3m24 36 7-8m-54 6 6 4"/><path d="m148 16 3 9 9 1-8 5v10l-7-7-10 2 5-9-4-7 10 2"/></>:<><path fill="#dce8cd" d="M48 129V66q-1-25 21-26 25-1 25 27v62m0-45h12V61q0-20 17-19 16 0 16 19v32q0 14-14 14H94M48 95H31q-17 0-17-18V65q0-15 13-15 13 0 13 15v11h8"/><path fill="#e6a789" d="M35 129h75l-9 28H46Z"/><path d="M67 61v8m9 11v8m-15 13v8m62-42v8"/></>}</svg>}
function Landing({onJoin,connected,error}) {
 const [name,setName]=useState('');const [avatar,setAvatar]=useState(0);const [modal,setModal]=useState(null);const [code,setCode]=useState('');const [rounds,setRounds]=useState(3);const [duration,setDuration]=useState(60);const [localError,setLocalError]=useState('');
 useEffect(()=>{setName(localStorage.getItem('doodle-name')||'');const c=new URLSearchParams(location.search).get('room');if(c){setCode(c);setModal('join');}},[]);
 function join(mode){if(!name.trim()){setLocalError('A nickname is all you need to get started.');document.getElementById('nickname')?.focus();return;}setLocalError('');localStorage.setItem('doodle-name',name);onJoin({mode,name,avatar,code,settings:{rounds,duration}});}
 return <div className="site"><header className="header"><a className="brand" href="/" aria-label="Doodle Club home"><span className="brand-icon"><Pencil size={22}/></span>doodle<span className="brand-light">club</span><span className="brand-dot">✳</span></a><nav><button className="nav-link" onClick={()=>setModal('how')}><HelpCircle size={16}/> How to play</button><span className="nav-divider"/><span className="status"><i className={connected?'':'offline'}/>{connected?'All systems doodle':'Connecting…'}</span></nav></header>
 <main className="landing"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> GOOD TIMES, QUESTIONABLE ART.</div><h1>Little doodles.<br/>Big <span>laughs.<svg viewBox="0 0 280 20"><path d="M4 14Q124-2 275 9M35 19Q158 8 247 15"/></svg></span></h1><p>A drawing and guessing game for everyone.<br/>Grab your friends. Make a happy little mess.</p><div className="hero-notes"><span><Check size={14}/> Free to play</span><span><Check size={14}/> No downloads</span><span><Check size={14}/> Zero art skills needed</span></div></div>
 <div className="hero-art"><span className="art-label label-top">a masterpiece? debatable.</span><svg className="curved-arrow" viewBox="0 0 100 80"><path d="M8 4q77-6 67 61m-12-8 12 13 14-15"/></svg><div className="art-paper"><span className="paper-tape"/><Doodle type="flower" className="flower"/><span className="paper-caption">it's a sunflower, obviously.</span><span className="paper-spark">✧</span></div><Doodle type="pencil" className="hero-pencil"/><span className="floating-star">✳</span><div className="guess-bubble"><span className="tiny-avatar">🐸</span>sunflower!! <span className="bubble-check"><Check size={13}/></span></div><div className="points-tag">+450 <Sparkles size={14}/></div><span className="art-label label-bottom">the fun? guaranteed.</span></div></section>
 <section className="play-section"><div className="section-title"><h2>Your next good time starts here<span>↴</span></h2><span>COME AS YOU ARE. DRAW AS YOU CAN.</span></div><div className="play-grid"><div className="identity-card"><div className="step-label">01 <span>MAKE YOURSELF AT HOME</span></div><div className="avatar-row"><button className="avatar-picker" onClick={()=>setAvatar((avatar+1)%avatars.length)} aria-label="Change avatar"><span>{avatars[avatar]}</span><i><Shuffle size={13}/></i></button><div><h3>Hey, you!</h3><p>Every artist needs a name.</p></div></div><label htmlFor="nickname">Your nickname</label><div className="name-input"><input id="nickname" value={name} maxLength={20} placeholder="A future Picasso…" onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')join('freeplay');}}/><Pencil size={15}/></div><div className="identity-foot"><span className="mini-spark">✦</span> New face? Tap your avatar to mix it up.</div></div>
 <div className="mode-card freeplay"><div className="mode-top"><span className="mode-icon"><Zap size={24}/></span><span className="pill"><i/> THE MORE, THE MERRIER</span></div><h3>Meet. Draw. Repeat.</h3><p>Jump into a room with new friends.<br/>Your next “what is that?” is waiting.</p><button className="button primary" disabled={!connected} onClick={()=>join('freeplay')}>Play Freeplay <ArrowRight size={18}/></button><span className="card-note"><Globe2 size={13}/> Public rooms · Up to 8 players</span></div>
 <div className="mode-card private"><div className="mode-top"><span className="mode-icon"><Users size={24}/></span><span className="hand-note">your people, your chaos <span>♡</span></span></div><h3>Bring the whole gang.</h3><p>A little room just for your people.<br/>Inside jokes very much encouraged.</p><button className="button dark" onClick={()=>{if(!name.trim()){setLocalError('Choose your nickname first, then bring your friends.');document.getElementById('nickname')?.focus();}else setModal('create');}}>Create a private room <Plus size={17}/></button><button className="join-link" onClick={()=>setModal('join')}>Got an invite? <b>Join a room</b> <ArrowUpRight size={13}/></button></div></div>{(localError||error)&&<div role="alert" className="error">{localError||error}</div>}</section>
 <section className="how-strip"><div className="how-title"><span className="little-loop">〰</span><h3>Simple rules.<br/>Endless possibilities.</h3><button onClick={()=>setModal('how')}>The very short version <ArrowUpRight size={13}/></button></div><div className="how-item"><span className="how-number yellow">1</span><div><h4>Pick a word</h4><p>Three choices. One big idea.</p></div><Pencil className="how-doodle" size={28}/></div><div className="how-item"><span className="how-number green">2</span><div><h4>Draw your heart out</h4><p>Stick figures are welcome here.</p></div><Heart className="how-doodle" size={30}/></div><div className="how-item"><span className="how-number purple">3</span><div><h4>Guess. Laugh. Win.</h4><p>Quick guesses, sweet points.</p></div><Trophy className="how-doodle" size={28}/></div></section>
 <div className="bottom-note"><Doodle type="planet"/><p>A little less scrolling. <span>A little more scribbling.</span></p><span className="scribble">✷</span></div>
 </main><footer><span>Made for the fun of it. <Heart size={12}/></span><span>Be kind. Get creative. Stay a little weird.</span><span>© {new Date().getFullYear()} Doodle Club</span></footer>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="close icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button><span className="modal-symbol">{modal==='how'?'✏️':modal==='join'?'💌':'🏡'}</span><h2 id="modal-title">{modal==='how'?'Small rules. Big fun.':modal==='join'?'You’re invited.':'A room for your people.'}</h2>{modal==='how'?<><p>Bring at least one other player, then take turns making your best (or worst) art.</p><ol className="rules"><li>Choose one of three words. You have 15 seconds to decide.</li><li>Draw using the shared canvas. No letters or spelling it out!</li><li>Everyone else guesses in chat. Faster correct guesses earn more points.</li><li>The artist gets 75 points for every successful guess. After all rounds, the most points wins.</li></ol><button className="button primary" onClick={()=>setModal(null)}>Let’s doodle <ArrowRight size={17}/></button></>:<><p>{modal==='join'?'Paste your friend’s room code and make yourself at home.':'Send an invite, gather your friends, and let the doodling begin.'}</p>{modal==='join'?<><label>Your nickname<input value={name} onChange={e=>setName(e.target.value)} maxLength={20} placeholder="Your nickname"/></label><label>Room code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/></label></>:<div className="settings-grid"><label>Rounds<select value={rounds} onChange={e=>setRounds(+e.target.value)}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} rounds</option>)}</select></label><label>Time to draw<select value={duration} onChange={e=>setDuration(+e.target.value)}>{[30,45,60,90,120].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></label></div>}{(localError||error)&&<p className="error">{localError||error}</p>}<button className="button primary" disabled={!connected||(modal==='join'&&code.length!==6)} onClick={()=>join(modal==='join'?'join':'create')}>{modal==='join'?'Join the room':'Create room'} <ArrowRight size={17}/></button></>}</section></div>}
 </div>;
}
function Game({socket,room,onLeave}) {
 const canvas=useRef(null), last=useRef(null), chatEnd=useRef(null), roomRef=useRef(room);roomRef.current=room;
 const [color,setColor]=useState(colors[0]),[size,setSize]=useState(6),[guess,setGuess]=useState(''),[now,setNow]=useState(Date.now()),[copied,setCopied]=useState(false);
 const me=socket.id, drawing=room.drawerId===me&&room.status==='drawing', drawer=room.players.find(p=>p.id===room.drawerId), remaining=Math.max(0,Math.ceil((room.deadline-now)/1000));
 function draw(s){const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');ctx.beginPath();ctx.strokeStyle=s.color;ctx.lineWidth=s.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.moveTo(s.from[0]*c.width,s.from[1]*c.height);ctx.lineTo(s.to[0]*c.width,s.to[1]*c.height);ctx.stroke();}
 function redraw(){const c=canvas.current;if(c){c.getContext('2d').clearRect(0,0,c.width,c.height);roomRef.current.strokes.forEach(draw);}}
 useEffect(()=>{redraw();},[room.strokes,room.status]);
 useEffect(()=>{const stroke=s=>{roomRef.current.strokes.push(s);draw(s);};const clear=()=>{roomRef.current.strokes=[];redraw();};socket.on('stroke',stroke);socket.on('clear',clear);const t=setInterval(()=>setNow(Date.now()),250);return()=>{socket.off('stroke',stroke);socket.off('clear',clear);clearInterval(t);};},[socket]);
 useEffect(()=>{const list=chatEnd.current?.parentElement;if(list)list.scrollTop=list.scrollHeight;},[room.messages.length]);
 function point(e){const r=canvas.current.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
 function move(e){if(!drawing||!last.current)return;const p=point(e);const s={from:last.current,to:p,color,size};draw(s);roomRef.current.strokes.push(s);socket.emit('stroke',s);last.current=p;}
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.id}`);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setCopied(false);}}
 const sorted=[...room.players].sort((a,b)=>b.score-a.score);
 return <div className="game-page"><header className="header"><a className="brand" href="/" onClick={e=>{e.preventDefault();onLeave();}}><span className="brand-icon"><Pencil size={22}/></span>doodle<span className="brand-light">club</span><span className="brand-dot">✳</span></a><nav><button className="room-code" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Invite copied':`Room ${room.id}`}</button><button className="nav-link" onClick={onLeave}><LogOut size={16}/> Leave room</button></nav></header><main className="game-main"><div className="game-heading"><div><div className="eyebrow">{room.kind==='public'?'A FEW NEW FRIENDS. A LOT OF DOODLES.':'YOUR PEOPLE. YOUR LITTLE CREATIVE CORNER.'}</div><h1>{room.status==='lobby'?'The gang’s getting together.':room.status==='finished'?'That was a work of art.':'Make a happy little mess.'}</h1></div><span className="round-badge"><Sparkles size={16}/> Round {room.round||1} / {room.rounds}</span></div><div className="game-grid"><aside className="players-panel"><div className="panel-title"><h3>The club</h3><span><Users size={14}/> {room.players.length}/8</span></div>{sorted.map((p,i)=><div className={`player ${p.id===room.drawerId?'active':''}`} key={p.id}><span className="player-avatar">{avatars[p.avatar]}</span><div><strong>{p.name} {p.id===me&&<small>(you)</small>}</strong><span>{p.guessed?'Got it! ✨':p.id===room.drawerId?'At the drawing board':`${p.score} points`}</span></div>{p.id===room.hostId&&<Crown size={14}/>}</div>)}<div className="invite-box"><span>Good doodles need good company.</span><button onClick={copy}>{copied?'Copied!':'Invite a friend'} <Plus size={14}/></button></div><div className="room-settings"><Settings2 size={14}/> {room.rounds} rounds · {room.duration}s per turn</div></aside>
 <section className="canvas-panel"><div className="canvas-bar"><span>{room.status==='lobby'?<><span className="live-dot"/> Waiting for friends</>:room.status==='choosing'?<><Pencil size={15}/> {drawer?.name} is choosing</>:room.status==='finished'?<><Trophy size={16}/> Final results</>:<><Pencil size={15}/> {drawing?'You’re drawing':`${drawer?.name||'Someone'} is drawing`}</>}</span><strong className="word-hint">{room.status==='drawing'?(room.word||room.hint):room.status==='reveal'?room.word:''}</strong>{room.deadline>0&&<span className={`timer ${remaining<10?'urgent':''}`}><Timer size={16}/>{remaining}s</span>}</div><div className="canvas-wrap"><canvas ref={canvas} width={1000} height={680} onPointerDown={e=>{if(drawing){e.currentTarget.setPointerCapture(e.pointerId);last.current=point(e);move(e);}}} onPointerMove={move} onPointerUp={()=>last.current=null} onPointerCancel={()=>last.current=null}/>
 {room.status==='lobby'&&<div className="canvas-overlay lobby-overlay"><Doodle type="flower"/><h2>Great company. Blank canvas.</h2><p>{room.players.length<2?'Invite a friend to get the first doodle going.':'Everyone’s here? Let the happy accidents begin.'}</p><div className="invite-code"><span>YOUR ROOM CODE</span><strong>{room.id}</strong><button onClick={copy} aria-label="Copy room invite">{copied?<Check size={18}/>:<Copy size={18}/>}</button></div>{room.hostId===me?<button className="button primary" disabled={room.players.length<2} onClick={()=>socket.emit('start')}>{room.players.length<2?'Waiting for one more player…':'Let’s play'} <ArrowRight size={17}/></button>:<p className="small-muted">Your host will start the game soon.</p>}{room.kind==='public'&&<p className="small-muted">Matchmaking is open. Play starts when someone joins.</p>}</div>}
 {room.status==='choosing'&&<div className="canvas-overlay"><span className="big-emoji">🤔</span><h2>{room.drawerId===me?'What’s your masterpiece?':`${drawer?.name} is finding inspiration…`}</h2><p>{room.drawerId===me?'Pick a word. Trust your inner artist.':'Get your guessing fingers ready.'}</p><div className="word-choices">{room.choices.map(w=><button key={w} onClick={()=>socket.emit('choose',w)}>{w}<ArrowUpRight size={16}/></button>)}</div></div>}
 {room.status==='reveal'&&<div className="reveal-banner"><Sparkles size={20}/><div>It was <strong>{room.word}</strong>!<span>{room.guessed.length} correct {room.guessed.length===1?'guess':'guesses'} · Next turn in {remaining}s</span></div></div>}
 {room.status==='finished'&&<div className="canvas-overlay results"><span className="big-emoji">🏆</span><h2>{sorted[0]?.name} takes the crown!</h2><p>But honestly? You’re all a little bit Picasso.</p><div className="leaderboard">{sorted.map((p,i)=><div key={p.id}><b>{i+1}</b><span>{avatars[p.avatar]}</span><strong>{p.name}</strong><span>{p.score} pts</span></div>)}</div>{room.hostId===me?<button className="button primary" disabled={room.players.length<2} onClick={()=>socket.emit('start')}>One more masterpiece? <ArrowRight size={16}/></button>:<p>Waiting for your host to play again.</p>}</div>}
 </div><div className={`drawing-toolbar ${!drawing?'disabled-tools':''}`}><div className="palette">{colors.map(c=><button key={c} disabled={!drawing} onClick={()=>setColor(c)} aria-label={`Draw in ${c}`} className={color===c?'selected':''} style={{background:c}}/>)}</div><div className="tool-divider"/><select aria-label="Brush size" value={size} disabled={!drawing} onChange={e=>setSize(+e.target.value)}><option value="3">Fine</option><option value="6">Medium</option><option value="14">Bold</option><option value="30">Extra bold</option></select><button className={`icon-button ${color==='#ffffff'?'selected-tool':''}`} disabled={!drawing} aria-label="Eraser" onClick={()=>{setColor('#ffffff');setSize(30);}}><Eraser size={19}/></button><button className="icon-button" disabled={!drawing} aria-label="Clear canvas" onClick={()=>socket.emit('clear')}><Trash2 size={18}/></button></div><div className="canvas-tip">{drawing?'Your canvas, your rules. (Except no writing the word!)':'A little imagination goes a long way. Keep those guesses coming.'}</div></section>
 <aside className="chat-panel"><div className="panel-title"><h3>Guesses & good vibes</h3><MessageCircle size={17}/></div><div className="messages">{room.messages.map(m=><div key={m.id} className={`chat-message ${m.type}`}>{m.type==='chat'?<><strong>{m.name}</strong><span>{m.text}</span></>:m.text}</div>)}<div ref={chatEnd}/></div><form onSubmit={e=>{e.preventDefault();if(guess.trim()){socket.emit('chat',guess);setGuess('');}}}><input aria-label="Your guess or chat message" maxLength={160} value={guess} disabled={room.status==='drawing'&&(drawing||room.guessed.includes(me))} onChange={e=>setGuess(e.target.value)} placeholder={drawing?'Let your drawing do the talking':room.guessed.includes(me)&&room.status==='drawing'?'You got it! Nice work.':'Type your guess…'}/><button aria-label="Send message" disabled={!guess.trim()}><Send size={17}/></button></form><span className="chat-note">Be kind. Wild guesses welcome.</span></aside></div></main></div>;
}
export default function Home(){const [socket,setSocket]=useState(null),[connected,setConnected]=useState(false),[room,setRoom]=useState(null),[error,setError]=useState('');useEffect(()=>{const s=io();setSocket(s);s.on('connect',()=>setConnected(true));s.on('disconnect',()=>{setConnected(false);setRoom(null);setError('Connection lost. Rejoin your room when you’re connected.');});s.on('room',r=>{setRoom(r);setError('');});return()=>s.disconnect();},[]);function join(data){setError('');socket?.emit('join',data,result=>{if(result.error)setError(result.error);});}return room&&socket?<Game socket={socket} room={room} onLeave={()=>{socket.emit('leave');setRoom(null);history.replaceState(null,'','/');}}/>:<Landing onJoin={join} connected={connected} error={error}/>;}
