import { randomUUID, randomInt } from 'node:crypto';
export const WORDS = [
 'man sleeping',
 'someone dancing',
 'eating pizza',
 'walking a dog',
 'monkey driving',
 'cat using computer',
 'dog wearing sunglasses',
 'alien drinking coffee',
 'penguin swimming',
 'robot cooking',
 'grandma gaming',
 'zombie shopping',
 'pirate taking a selfie',
 'astronaut eating burger',
 'dragon sleeping',
 'baby driving a car',
 'cow flying',
 'fish riding a bicycle',
 'chicken playing guitar',
 'monkey taking a photo',
 'apple',
 'ball',
 'cat',
 'dog',
 'sun',
 'moon',
 'star',
 'tree',
 'house',
 'car',
 'bus',
 'bike',
 'book',
 'pen',
 'chair',
 'table',
 'phone',
 'clock',
 'key',
 'cup',
 'shoe',
 'hat',
 'bed',
 'door',
 'window',
 'cake',
 'pizza',
 'burger',
 'ice cream',
 'flower',
 'fish',
 'bird',
 'cloud',
 'rain',
 'fire',
 'boat',
 'plane',
 'train',
 'pineapple',
 'astronaut',
 'volcano',
 'jellyfish',
 'skateboard',
 'campfire',
 'cactus',
 'rainbow',
 'octopus',
 'lighthouse',
 'snowman',
 'butterfly',
 'spaceship',
 'watermelon',
 'guitar',
 'penguin',
 'treehouse',
 'umbrella',
 'dinosaur',
 'robot',
 'treasure',
 'mermaid',
 'dragon',
 'sunflower',
 'hot air balloon',
 'roller coaster',
 'birthday cake',
 'submarine',
 'hedgehog',
 'telescope',
 'sailboat',
 'mushroom',
 'fireworks',
 'elephant',
 'sandcastle',
 'unicorn',
 'popcorn',
 'helicopter',
 'koala',
 'pancakes',
 'windmill',
 'suitcase',
 'toothbrush',
 'crocodile',
 'backpack',
 'headphones',
 'basketball',
 'flamingo',
];
export const TRUTH_PROMPTS = [
 "What is your most used emoji?",
 "What's your favorite food?",
 "What's the funniest thing you've done recently?",
 "What's your favorite movie?",
 "What's your dream vacation?",
 "What is your biggest pet peeve?",
 "What's the weirdest food you've tried?",
 "What's your favorite song right now?",
 "What is something you can't live without?",
 "What's your hidden talent?",
 "What's the last thing you searched online?",
 "What's your favorite game?",
 "What's your most embarrassing nickname?",
 "What's the funniest nickname you've given someone?",
 "What's your favorite childhood memory?",
 "What is your biggest fear?",
 "What's your dream job?",
 "What's one thing you're really good at?",
 "What's one thing you're terrible at?",
 "What's the strangest dream you've had?",
 "Have you ever talked to yourself in the mirror?",
 "What's the dumbest thing you've ever done?",
 "Have you ever waved back at someone who wasn't waving at you?",
 "Have you ever fallen in public?",
 "What's the weirdest thing you've done when nobody was watching?",
 "Have you ever laughed at the wrong moment?",
 "What's the most embarrassing autocorrect you've sent?",
 "Have you ever pretended to understand something you didn't?",
 "What's the weirdest thing in your room right now?",
 "Have you ever blamed someone else for something you did?",
 "What's your funniest childhood story?",
 "Have you ever sung in the shower?",
 "Have you ever practiced an argument in your head?",
 "What's the weirdest food combination you actually like?",
 "Have you ever sent a message to the wrong person?",
 "Who was your first crush?",
 "What was your biggest crush mistake?",
 "Have you ever liked someone and never told them?",
 "What's your idea of a perfect date?",
 "What's the first thing you notice about someone?",
 "Have you ever had a crush on a friend?",
 "Have you ever stalked someone's social media?",
 "What's the sweetest thing someone has done for you?",
 "Have you ever received a message that made your whole day?",
 "What's your biggest green flag in someone?",
 "What's your biggest red flag in someone?",
 "Have you ever pretended not to like someone?",
 "Would you date your best friend?",
 "What's your biggest relationship fear?",
 "Have you ever fallen for someone unexpectedly?",
 "What's one secret talent you have?",
 "What's one thing you've never told your friends?",
 "What's something you wish you could change about yourself?",
 "What's one decision you regret?",
 "What's something you're proud of?",
 "What's something you've always wanted to try?",
 "What's the biggest risk you've taken?",
 "What's something you pretend to like?",
 "What's something that instantly annoys you?",
 "What's one thing people misunderstand about you?",
 "What's the biggest lie you've told to get out of something?",
 "What's something you've done that nobody expected?",
 "What's one habit you'd like to break?",
 "What's something you wish you had learned earlier?",
 "What's your biggest irrational fear?",
 "What's your favorite game of all time?",
 "What's the worst game you've ever played?",
 "Have you ever rage-quit?",
 "What's your longest gaming session?",
 "Have you ever broken something because of a game?",
 "What's your favorite game character?",
 "What's your favorite gaming console?",
 "Have you ever lied about being good at a game?",
 "What's your most embarrassing gaming moment?",
 "Have you ever blamed lag when you actually lost?",
 "What's your favorite multiplayer game?",
 "Have you ever cheated in a game?",
 "What's the most expensive gaming purchase you've made?",
 "What's your favorite game soundtrack?",
 "What's your dream gaming setup?",
];
export const DARE_PROMPTS = [
 'Do 10 jumping jacks.',
 'Do your best dance for 15 seconds.',
 'Make a funny face.',
 'Sing the chorus of your favorite song.',
 'Speak in a robot voice for one round.',
 'Act like a cat for 20 seconds.',
 'Do your best evil laugh.',
 "Pretend you're a news reporter.",
 'Walk like a model for 10 seconds.',
 'Do your best superhero pose.',
 'Say the alphabet backwards as far as you can.',
 'Try to touch your nose with your tongue.',
 "Pretend you're a famous actor.",
 'Do five squats.',
 'Make an animal sound and let everyone guess it.',
 'Talk without using the letter "E" for 30 seconds.',
 'Pretend to be a teacher.',
 'Do a dramatic movie scene.',
 'Freeze like a statue for 30 seconds.',
 'Tell a joke in your most serious voice.',
 'Talk like a pirate for one minute.',
 "Pretend you're a chicken.",
 'Do your worst dance.',
 'Sing a song using only "la la la."',
 'Pretend your chair is a race car.',
 'Give a dramatic speech about a spoon.',
 "Act like you're being interviewed after winning the Olympics.",
 'Pretend to be an angry customer complaining about water.',
 'Do your best impression of another player.',
 'Speak like a robot until your next turn.',
 "Pretend you're a superhero who has no powers.",
 "Act like you're walking on the moon.",
 "Pretend you're a celebrity avoiding paparazzi.",
 'Sell an imaginary product to the group.',
 'Give a motivational speech to a potato.',
 "Pretend you're a villain explaining your evil plan.",
 'Do a slow-motion action scene.',
 "Pretend you're a waiter serving invisible food.",
 "Act like you're trapped inside a video game.",
 'Make up a ridiculous new dance move.',
 'Everyone does 5 jumping jacks.',
 'Everyone makes the same funny face.',
 'Everyone says one random word at the same time.',
 'Everyone dances for 10 seconds.',
 'Everyone talks like a robot for one round.',
 'Everyone makes an animal sound.',
 'Everyone gives the player a funny nickname.',
 'Everyone votes for the funniest player.',
 'Everyone tells one embarrassing story.',
 'Everyone does their best villain laugh.',
 'Everyone says their favorite movie.',
 'Everyone chooses someone to imitate.',
 'Everyone does a superhero pose.',
 'Everyone creates a team handshake.',
 'Everyone has to rhyme their next sentence.',
 'Play your next turn with one hand.',
 'Talk like an NPC for one round.',
 'Pretend you just defeated the final boss.',
 'Give yourself a ridiculous gamer name.',
 'Explain your last game like a sports commentator.',
 "Pretend you're a professional streamer.",
 'Celebrate your next correct answer like you won a championship.',
 'Do a dramatic rage-quit and immediately come back.',
 'Give another player a funny achievement.',
 'Narrate everything you do for 30 seconds.',
 "Pretend you're an NPC giving a quest.",
 'Make your best victory speech.',
 'Describe yourself as a video-game character.',
 'Invent a ridiculous game power.',
 'Create a fake game trailer in 20 seconds.',
];
export function normalize(value) { return String(value).toLowerCase().trim().replace(/\s+/g, ' '); }
export function guessPoints(remaining, duration) { return 1 + Math.round(9 * Math.max(0, Math.min(1, remaining / duration))); }
export function choices() { const pool = [...WORDS]; return Array.from({length:3}, () => pool.splice(randomInt(pool.length),1)[0]); }
function pickMany(list, count) { const pool=[...list]; return Array.from({length:count},()=>pool.splice(randomInt(pool.length),1)[0]); }
export function truthDareOptions() { return { truth:pickMany(TRUTH_PROMPTS,2), dare:pickMany(DARE_PROMPTS,2) }; }
export function createRoom(host, settings = {}, kind = 'private') {
 return { id:randomUUID().slice(0,6).toUpperCase(), kind, hostId:host.id, players:[host], status:'lobby', round:0, rounds:Math.max(1,Math.min(8,Math.floor(Number(settings.rounds))||3)), duration:Math.max(30,Math.min(120,Math.floor(Number(settings.duration))||60)), truthDare:Boolean(settings.truthDare), challenge:null, maxPlayers:8, drawerId:null, word:null, choices:[], guessed:[], strokes:[], messages:[], turnOrder:[], turnIndex:-1, deadline:0 };
}
export function publicRoom(room, viewer) {
 const { word, choices: words, timer, turnOrder, ...safe } = room;
 const knows = viewer === room.drawerId || room.guessed.includes(viewer) || ['reveal','finished'].includes(room.status);
 return { ...safe, word:knows ? word : null, choices: viewer === room.drawerId && room.status === 'choosing' ? words : [], hint:word ? [...word].map(c=>c===' '?'  ':'_').join(' ') : '', players:room.players.map(p=>({...p, guessed:room.guessed.includes(p.id)})) };
}
